openapi: '3.0.2'
info:
  title: TimeWeaver API
  version: '1.0'
  description: 'REST API for server side operations for TimeWeaver.'
  contact:
    name: 'Nick LaPrell'
    email: 'njlaprell@gmail.com'
  license:
    name: 'MIT License'
servers:
  - url: https://timeweaver-dev.laprell.org
  - url: https://timeweaver.laprell.org

components:
  securitySchemes:
    googleOauth2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://accounts.google.com/o/oauth2/auth
          tokenUrl: https://oauth2.googleapis.com/token
          scopes:
            profile: Read the Google profile
            email: Read the email address.
paths:
  /auth:
    get:
      responses:
        '200':
          description: OK
security:
  - googleOauth2:
      - profile
      - email
